#!/usr/bin/env python3
"""Codemap generator (pipeline Phase 3). Invoked by scripts/refresh-codemap.

Inputs : dist-newstyle hoogle txt (cabal haddock --haddock-hoogle output),
         codemap/capabilities.yaml (curated)
Outputs: codemap/signatures/*.txt (committed, CI sync-checked)
         codemap/MAP.md (committed render)
         codemap/.doc-ratchet (module-header + exported-function counters)

CANONICALIZATION: haddock's hoogle output is NOT byte-stable across platforms
(Linux emits fewer doc comments than macOS — observed 2026-07-07). Signature
files are therefore stripped to pure API surface (doc/blank lines dropped),
and the doc-ratchet is derived from SOURCE files (grep-based), so every
committed artifact is platform-independent and the CI sync check can be exact.
"""

import glob
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SIG = ROOT / "codemap" / "signatures"

# Namespace split: keep individual files grep-sized for one-Read access.
def bucket(module: str) -> str:
    if module.startswith(("Service", "Integration.")) or module == "Integration":
        return "nhcore-service"
    if module.startswith(("Test", "Auth", "Config")):
        return "nhcore-auth-config-testlib"
    return "nhcore-core"


def split_hoogle():
    txts = {}
    for pattern, name in [("**/nhcore-*/**/nhcore.txt", "nhcore"),
                          ("**/nhintegrations-*/**/nhintegrations.txt", "nhintegrations")]:
        hits = glob.glob(str(ROOT / "dist-newstyle" / pattern), recursive=True)
        if not hits:
            sys.exit(f"codemap: no hoogle txt for {name} — run cabal haddock --haddock-hoogle first")
        txts[name] = Path(sorted(hits)[-1]).read_text(encoding="utf-8")

    SIG.mkdir(parents=True, exist_ok=True)
    # canonical structure: {bucket: {module: sorted entries}} — haddock's
    # emission ORDER also varies across platforms (observed: re-export
    # position drift), so both modules and their entries are sorted.
    buckets: dict[str, dict[str, list[str]]] = {}
    stats = {"modules": 0, "exports": 0}

    for pkg, text in txts.items():
        current = None
        for line in text.split("\n"):
            # pure API surface — doc/blank lines dropped (doc emission is
            # platform-dependent; see module docstring)
            if line.startswith("--") or not line.strip():
                continue
            m = re.match(r"^module ([A-Za-z0-9.]+)", line)
            if m:
                current = m.group(1)
                stats["modules"] += 1
            if current is None:
                continue
            key = "nhintegrations" if pkg == "nhintegrations" else bucket(current)
            buckets.setdefault(key, {}).setdefault(current, [])
            if not m:
                buckets[key][current].append(line)
            if re.match(r"^[a-z_(\[][^:]*::", line):
                stats["exports"] += 1

    banner = ("-- GENERATED by ./dev codemap — do not edit. Pure API surface, "
              "modules and entries sorted (platform-stable canonical form). "
              "Source of truth: the Haskell modules.\n")
    for key, mods in buckets.items():
        out = [banner]
        for module in sorted(mods):
            out.append(f"module {module}")
            out.extend(sorted(set(mods[module])))
            out.append("")
        (SIG / f"{key}.txt").write_text("\n".join(out).strip() + "\n", encoding="utf-8")
    return stats


def ratchet_from_source():
    """Doc-ratchet counters derived from SOURCE (platform-independent):
    - undocumented_modules: exposed modules whose `module` decl is not
      preceded by a `-- |` haddock block
    - undocumented_exports: top-level type signatures not immediately
      preceded by a comment line"""
    sys.path.insert(0, str(ROOT / "codemap"))
    from check import exposed_modules  # single source of module resolution
    undoc_mods, undoc_exports = 0, 0
    for _mod, path in exposed_modules():
        lines = (ROOT / path).read_text(encoding="utf-8").split("\n")
        header_doc = False
        prev_comment = False
        for line in lines:
            if re.match(r"^module\b", line):
                if not header_doc:
                    undoc_mods += 1
                break
            if line.startswith("-- |"):
                header_doc = True
        for line in lines:
            if re.match(r"^[a-z_][A-Za-z0-9_']*\s*::", line) and not prev_comment:
                undoc_exports += 1
            prev_comment = line.strip().startswith("--")
    return undoc_mods, undoc_exports


def render_map():
    data = yaml.safe_load((ROOT / "codemap" / "capabilities.yaml").read_text())
    ext = yaml.safe_load((ROOT / "codemap" / "extension-points.yaml").read_text())
    out = ["<!-- GENERATED by ./dev codemap from capabilities.yaml + extension-points.yaml — do not edit. -->",
           "# NeoHaskell code map", "",
           "Routing: pick capability IDs from this closed list (aliases bridge intent",
           "vocabulary); for NEW code use the extension points. Full contract: codemap/README.md.",
           "", "## Capabilities", "",
           "| id | responsibility | owns | risk |"
           , "|---|---|---|---|"]
    for c in data["capabilities"]:
        risk = " ".join(t for t in ["🔒" if c.get("security-sensitive") else "",
                                    "⚡" if c.get("perf-sensitive") else ""] if t)
        out.append(f"| `{c['id']}` | {c['responsibility'].split('—')[0].strip()} | `{c['owns'][0]}`{'…' if len(c['owns'])>1 else ''} | {risk} |")
    out += ["", "## Extension points (where NEW things go)", "",
            "| kind | create | register | tests |", "|---|---|---|---|"]
    for e in ext["extension-points"]:
        out.append(f"| `{e['kind']}` | `{e['create'][0]}` | {', '.join('`'+r+'`' for r in e['register'])} | `{e['tests'][0]}` |")
    (ROOT / "codemap" / "MAP.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    return len(data["capabilities"]), len(ext["extension-points"])


def main():
    stats = split_hoogle()
    ncap, next_ = render_map()
    undoc_mods, undoc_exports = ratchet_from_source()
    ratchet = (ROOT / "codemap" / ".doc-ratchet")
    ratchet.write_text(
        "# doc-ratchet: counters may DECREASE only (CI-enforced by check.py).\n"
        "# Source-derived (platform-independent) — see generate.py.\n"
        f"undocumented_modules: {undoc_mods}\n"
        f"undocumented_exports: {undoc_exports}\n")
    print(f"codemap: {stats['modules']} modules / {stats['exports']} exports → "
          f"{len(list(SIG.glob('*.txt')))} signature files; "
          f"{ncap} capabilities + {next_} extension points → MAP.md; "
          f"ratchet(source-derived): {undoc_mods} undocumented modules, "
          f"{undoc_exports} undocumented exports")


if __name__ == "__main__":
    main()
