#!/usr/bin/env python3
"""Codemap generator (pipeline Phase 3). Invoked by scripts/refresh-codemap.

Inputs : dist-newstyle hoogle txt (cabal haddock --haddock-hoogle output),
         codemap/capabilities.yaml (curated)
Outputs: codemap/signatures/*.txt (committed, CI sync-checked)
         codemap/MAP.md (committed render)
         codemap/.doc-ratchet (module-header + exported-function counters)

CANONICALIZATION: haddock's hoogle output is NOT byte-stable across platforms
(Linux emits fewer doc comments than macOS — observed 2026-07-07). Signature
files are therefore stripped to pure API surface (doc/blank lines dropped),
and the doc-ratchet is derived from SOURCE files (grep-based), so every
committed artifact is platform-independent and the CI sync check can be exact.
"""

import glob
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SIG = ROOT / "codemap" / "signatures"

# Namespace split: keep individual files grep-sized for one-Read access.
def bucket(module: str) -> str:
    if module.startswith(("Service", "Integration.")) or module == "Integration":
        return "nhcore-service"
    if module.startswith(("Test", "Auth", "Config")):
        return "nhcore-auth-config-testlib"
    return "nhcore-core"


def split_hoogle():
    txts = {}
    for pattern, name in [("**/nhcore-*/**/nhcore.txt", "nhcore"),
                          ("**/nhintegrations-*/**/nhintegrations.txt", "nhintegrations")]:
        hits = glob.glob(str(ROOT / "dist-newstyle" / pattern), recursive=True)
        if not hits:
            sys.exit(f"codemap: no hoogle txt for {name} — run cabal haddock --haddock-hoogle first")
        txts[name] = Path(sorted(hits)[-1]).read_text(encoding="utf-8")

    SIG.mkdir(parents=True, exist_ok=True)
    # canonical structure: {bucket: {module: sorted entries}} — haddock's
    # emission ORDER also varies across platforms (observed: re-export
    # position drift), so both modules and their entries are sorted.
    buckets: dict[str, dict[str, list[str]]] = {}
    stats = {"modules": 0, "exports": 0}

    for pkg, text in txts.items():
        current = None
        for line in text.split("\n"):
            # pure API surface — doc/blank lines dropped (doc emission is
            # platform-dependent; see module docstring)
            if line.startswith("--") or not line.strip():
                continue
            m = re.match(r"^module ([A-Za-z0-9.]+)", line)
            if m:
                current = m.group(1)
                stats["modules"] += 1
            if current is None:
                continue
            key = "nhintegrations" if pkg == "nhintegrations" else bucket(current)
            buckets.setdefault(key, {}).setdefault(current, [])
            if not m:
                buckets[key][current].append(line)
            if re.match(r"^[a-z_(\[][^:]*::", line):
                stats["exports"] += 1

    banner = ("-- GENERATED by ./dev codemap — do not edit. Pure API surface, "
              "modules and entries sorted (platform-stable canonical form). "
              "Source of truth: the Haskell modules.\n")
    for key, mods in buckets.items():
        out = [banner]
        for module in sorted(mods):
            out.append(f"module {module}")
            out.extend(sorted(set(mods[module])))
            out.append("")
        (SIG / f"{key}.txt").write_text("\n".join(out).strip() + "\n", encoding="utf-8")
    return stats


def ratchet_from_source():
    """Doc-ratchet counters derived from SOURCE (platform-independent):
    - undocumented_modules: exposed modules whose `module` decl is not
      preceded by a `-- |` haddock block
    - undocumented_exports: top-level type signatures not immediately
      preceded by a comment line"""
    sys.path.insert(0, str(ROOT / "codemap"))
    from check import exposed_modules  # single source of module resolution
    undoc_mods, undoc_exports = 0, 0
    for _mod, path in exposed_modules():
        lines = (ROOT / path).read_text(encoding="utf-8").split("\n")
        header_doc = False
        prev_comment = False
        for line in lines:
            if re.match(r"^module\b", line):
                if not header_doc:
                    undoc_mods += 1
                break
            if line.startswith("-- |"):
                header_doc = True
        for line in lines:
            if re.match(r"^[a-z_][A-Za-z0-9_']*\s*::", line) and not prev_comment:
                undoc_exports += 1
            prev_comment = line.strip().startswith("--")
    return undoc_mods, undoc_exports


QUALIFIED_CALL = re.compile(r"\b([A-Z][A-Za-z0-9]*)\.([a-z][A-Za-z0-9_']*)")
DOCTEST_START = re.compile(r"^\s*--\s+>>>\s?(.*)")
DOCTEST_CONT = re.compile(r"^\s*--\s?(?!\s*>>>)(.*)")


_TRACKED_CACHE = None


def _tracked_hs():
    global _TRACKED_CACHE
    if _TRACKED_CACHE is None:
        import subprocess
        _TRACKED_CACHE = [f for f in subprocess.run(
            ["git", "ls-files", "*.hs"], capture_output=True,
            text=True, cwd=ROOT).stdout.splitlines()
            if not f.startswith("docs/archive/")]
    return _TRACKED_CACHE


def _signature_index():
    """{(module_last_segment, fn_name): (full_module, sig_line)} from the
    generated signature files; ambiguous last-segments resolved by preferring
    the module whose full name equals the alias (core modules: Text, Array…)."""
    idx = {}
    for txt in sorted(SIG.glob("*.txt")):
        module = None
        for line in txt.read_text(encoding="utf-8").splitlines():
            m = re.match(r"^module ([A-Za-z0-9.]+)", line)
            if m:
                module = m.group(1)
                continue
            s = re.match(r"^([a-z_][A-Za-z0-9_']*) ::", line)
            if s and module:
                key = (module.split(".")[-1], s.group(1))
                best = idx.get(key)
                # prefer exact alias==full-module (e.g. Text over Data-like nested)
                if best is None or module == key[0]:
                    idx[key] = (module, line)
    return idx


def _doctest_for(path: Path, fn: str):
    """First doctest example from the doc block immediately above `fn ::`."""
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except Exception:
        return None
    for i, line in enumerate(lines):
        if re.match(rf"^{re.escape(fn)}\s*::", line):
            # walk back through the comment block above
            block = []
            j = i - 1
            while j >= 0 and (lines[j].strip().startswith("--") or not lines[j].strip()):
                if not lines[j].strip() and block:
                    break
                block.append(lines[j])
                j -= 1
            block.reverse()
            example = []
            for b in block:
                dm = DOCTEST_START.match(b)
                if dm:
                    example = [">>> " + dm.group(1)]
                elif example:
                    cm = DOCTEST_CONT.match(b)
                    if cm and cm.group(1).strip():
                        example.append(cm.group(1).strip())
                        break  # first result line is enough
            if example:
                return example
            return None
    return None


def _module_file(full_module: str):
    rel = full_module.replace(".", "/") + ".hs"
    for f in _tracked_hs():
        if f.endswith("/" + rel) or f == rel:
            return ROOT / f
    return None


def hot_card():
    """codemap/api-hot.md — frequency-ranked API card. Counts qualified call
    sites across the repo, resolves signatures, attaches doctest examples."""
    import collections
    counts = collections.Counter()
    for f in _tracked_hs():
        text = (ROOT / f).read_text(encoding="utf-8", errors="ignore")
        for line in text.splitlines():
            if line.lstrip().startswith("--") or line.lstrip().startswith("import"):
                continue
            for alias, fn in QUALIFIED_CALL.findall(line):
                counts[(alias, fn)] += 1

    idx = _signature_index()
    per_module = collections.defaultdict(list)
    for (alias, fn), n in counts.items():
        hit = idx.get((alias, fn))
        if hit:
            per_module[hit[0]].append((n, fn, hit[1]))

    module_totals = sorted(per_module.items(),
                           key=lambda kv: (-sum(n for n, _, _ in kv[1]), kv[0]))
    out = ["<!-- GENERATED by ./dev codemap — do not edit. Frequency-ranked from",
           "     actual call sites; examples mined from source doctests (CI-verified). -->",
           "# API hot card — the NeoHaskell you actually use", "",
           "Ranked by real call-site frequency. Consult BEFORE writing code;",
           "full surface: codemap/signatures/ · type-directed search: ./dev api \"<type>\"", ""]
    entries = 0
    for module, fns in module_totals[:18]:
        out.append(f"## {module}")
        src = _module_file(module)
        for n, fn, sig in sorted(fns, key=lambda t: (-t[0], t[1]))[:10]:
            out.append(f"- `{sig}`  <!-- {n} call sites -->")
            ex = _doctest_for(src, fn) if src else None
            if ex and len(ex) > 1:
                out.append(f"  - `{ex[0]}` → `{ex[1]}`")
            elif ex:
                out.append(f"  - `{ex[0]}`")
            entries += 1
        out.append("")
    (ROOT / "codemap" / "api-hot.md").write_text("\n".join(out).strip() + "\n", encoding="utf-8")
    return entries


def phrasebook():
    """codemap/phrasebook.md — every doctest in the exposed modules, grouped
    by capability (intent sections). Thin coverage = the doc backlog."""
    sys.path.insert(0, str(ROOT / "codemap"))
    from check import exposed_modules, owned_by, glob_to_re  # noqa: F401
    caps = yaml.safe_load((ROOT / "codemap" / "capabilities.yaml").read_text())["capabilities"]
    sections = {}
    no_doctests = []
    for mod, path in exposed_modules():
        lines = (ROOT / path).read_text(encoding="utf-8", errors="ignore").splitlines()
        examples = []
        current = None
        for line in lines:
            dm = DOCTEST_START.match(line)
            if dm:
                current = [">>> " + dm.group(1)]
                examples.append(current)
            elif current is not None:
                cm = DOCTEST_CONT.match(line)
                if cm and cm.group(1).strip():
                    current.append(cm.group(1).strip())
                else:
                    current = None
        owners = owned_by(path, caps)
        cap = owners[0] if owners else "(unmapped)"
        if examples:
            sections.setdefault(cap, {})[mod] = examples
        else:
            no_doctests.append(mod)

    out = ["<!-- GENERATED by ./dev codemap — do not edit. Mined from source",
           "     doctests (executed by ./dev doctest — these examples cannot lie). -->",
           "# NeoHaskell phrasebook — verified usage examples", ""]
    total = 0
    for cap in sorted(sections):
        out.append(f"## {cap}")
        for mod in sorted(sections[cap]):
            out.append(f"### {mod}")
            for ex in sections[cap][mod][:8]:
                out.append("```haskell")
                out.extend(ex[:4])
                out.append("```")
                total += 1
            extra = len(sections[cap][mod]) - 8
            if extra > 0:
                out.append(f"*… {extra} more doctests in the source module*")
        out.append("")
    out.append(f"---\n*{total} examples · modules with ZERO doctests: "
               f"{len(no_doctests)} (the documentation backlog — see codemap/.doc-ratchet)*")
    (ROOT / "codemap" / "phrasebook.md").write_text("\n".join(out).strip() + "\n", encoding="utf-8")
    return total, len(no_doctests)


def render_map():
    data = yaml.safe_load((ROOT / "codemap" / "capabilities.yaml").read_text())
    ext = yaml.safe_load((ROOT / "codemap" / "extension-points.yaml").read_text())
    out = ["<!-- GENERATED by ./dev codemap from capabilities.yaml + extension-points.yaml — do not edit. -->",
           "# NeoHaskell code map", "",
           "Routing: pick capability IDs from this closed list (aliases bridge intent",
           "vocabulary); for NEW code use the extension points. Full contract: codemap/README.md.",
           "", "## Capabilities", "",
           "| id | responsibility | owns | risk |"
           , "|---|---|---|---|"]
    for c in data["capabilities"]:
        risk = " ".join(t for t in ["🔒" if c.get("security-sensitive") else "",
                                    "⚡" if c.get("perf-sensitive") else ""] if t)
        out.append(f"| `{c['id']}` | {c['responsibility'].split('—')[0].strip()} | `{c['owns'][0]}`{'…' if len(c['owns'])>1 else ''} | {risk} |")
    out += ["", "## Extension points (where NEW things go)", "",
            "| kind | create | register | tests |", "|---|---|---|---|"]
    for e in ext["extension-points"]:
        out.append(f"| `{e['kind']}` | `{e['create'][0]}` | {', '.join('`'+r+'`' for r in e['register'])} | `{e['tests'][0]}` |")
    (ROOT / "codemap" / "MAP.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    return len(data["capabilities"]), len(ext["extension-points"])


def main():
    stats = split_hoogle()
    ncap, next_ = render_map()
    undoc_mods, undoc_exports = ratchet_from_source()
    hot_entries = hot_card()
    phrases, no_doc = phrasebook()
    ratchet = (ROOT / "codemap" / ".doc-ratchet")
    ratchet.write_text(
        "# doc-ratchet: counters may DECREASE only (CI-enforced by check.py).\n"
        "# Source-derived (platform-independent) — see generate.py.\n"
        f"undocumented_modules: {undoc_mods}\n"
        f"undocumented_exports: {undoc_exports}\n")
    print(f"codemap: {stats['modules']} modules / {stats['exports']} exports → "
          f"{len(list(SIG.glob('*.txt')))} signature files; "
          f"{ncap} capabilities + {next_} extension points → MAP.md; "
          f"ratchet(source-derived): {undoc_mods} undocumented modules, "
          f"{undoc_exports} undocumented exports; "
          f"hot card: {hot_entries} entries; phrasebook: {phrases} examples "
          f"({no_doc} modules without doctests)")


if __name__ == "__main__":
    main()
