#!/usr/bin/env python3
"""Codemap generator (pipeline Phase 3). Invoked by scripts/refresh-codemap.

Inputs : dist-newstyle hoogle txt (cabal haddock --haddock-hoogle output),
         codemap/capabilities.yaml (curated)
Outputs: codemap/signatures/*.txt (committed, CI sync-checked)
         codemap/MAP.md (committed render)
         codemap/.doc-ratchet (module-header + exported-function counters)
"""

import glob
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SIG = ROOT / "codemap" / "signatures"

# Namespace split: keep individual files grep-sized for one-Read access.
def bucket(module: str) -> str:
    if module.startswith(("Service", "Integration.")) or module == "Integration":
        return "nhcore-service"
    if module.startswith(("Test", "Auth", "Config")):
        return "nhcore-auth-config-testlib"
    return "nhcore-core"


def split_hoogle():
    txts = {}
    for pattern, name in [("**/nhcore-*/**/nhcore.txt", "nhcore"),
                          ("**/nhintegrations-*/**/nhintegrations.txt", "nhintegrations")]:
        hits = glob.glob(str(ROOT / "dist-newstyle" / pattern), recursive=True)
        if not hits:
            sys.exit(f"codemap: no hoogle txt for {name} — run cabal haddock --haddock-hoogle first")
        txts[name] = Path(sorted(hits)[-1]).read_text(encoding="utf-8")

    SIG.mkdir(parents=True, exist_ok=True)
    buckets: dict[str, list[str]] = {}
    stats = {"modules": 0, "undocumented_modules": 0,
             "exports": 0, "undocumented_exports": 0}

    for pkg, text in txts.items():
        current, doc_pending, module_doc = None, False, False
        chunks = text.split("\n")
        for i, line in enumerate(chunks):
            m = re.match(r"^module ([A-Za-z0-9.]+)", line)
            if m:
                current = m.group(1)
                stats["modules"] += 1
                # module doc = a "-- |" comment block immediately above
                module_doc = i > 0 and chunks[i - 1].startswith("--")
                if not module_doc:
                    stats["undocumented_modules"] += 1
                key = "nhintegrations" if pkg == "nhintegrations" else bucket(current)
                buckets.setdefault(key, []).append("")
            if current is None:
                continue
            key = "nhintegrations" if pkg == "nhintegrations" else bucket(current)
            buckets.setdefault(key, []).append(line)
            # exported entries = signature lines (name :: type) not comments
            if re.match(r"^[a-z_(\[][^:]*::", line):
                stats["exports"] += 1
                if not doc_pending:
                    stats["undocumented_exports"] += 1
            doc_pending = line.startswith("--")

    banner = ("-- GENERATED by ./dev codemap — do not edit. "
              "Source of truth: the Haskell modules.\n")
    for key, lines in buckets.items():
        (SIG / f"{key}.txt").write_text(banner + "\n".join(lines).strip() + "\n", encoding="utf-8")
    return stats


def render_map():
    data = yaml.safe_load((ROOT / "codemap" / "capabilities.yaml").read_text())
    ext = yaml.safe_load((ROOT / "codemap" / "extension-points.yaml").read_text())
    out = ["<!-- GENERATED by ./dev codemap from capabilities.yaml + extension-points.yaml — do not edit. -->",
           "# NeoHaskell code map", "",
           "Routing: pick capability IDs from this closed list (aliases bridge intent",
           "vocabulary); for NEW code use the extension points. Full contract: codemap/README.md.",
           "", "## Capabilities", "",
           "| id | responsibility | owns | risk |"
           , "|---|---|---|---|"]
    for c in data["capabilities"]:
        risk = " ".join(t for t in ["🔒" if c.get("security-sensitive") else "",
                                    "⚡" if c.get("perf-sensitive") else ""] if t)
        out.append(f"| `{c['id']}` | {c['responsibility'].split('—')[0].strip()} | `{c['owns'][0]}`{'…' if len(c['owns'])>1 else ''} | {risk} |")
    out += ["", "## Extension points (where NEW things go)", "",
            "| kind | create | register | tests |", "|---|---|---|---|"]
    for e in ext["extension-points"]:
        out.append(f"| `{e['kind']}` | `{e['create'][0]}` | {', '.join('`'+r+'`' for r in e['register'])} | `{e['tests'][0]}` |")
    (ROOT / "codemap" / "MAP.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    return len(data["capabilities"]), len(ext["extension-points"])


def main():
    stats = split_hoogle()
    ncap, next_ = render_map()
    ratchet = (ROOT / "codemap" / ".doc-ratchet")
    ratchet.write_text(
        "# doc-ratchet: counters may DECREASE only (CI-enforced by check.py)\n"
        f"undocumented_modules: {stats['undocumented_modules']}\n"
        f"undocumented_exports: {stats['undocumented_exports']}\n")
    print(f"codemap: {stats['modules']} modules / {stats['exports']} exports → "
          f"{len(list(SIG.glob('*.txt')))} signature files; "
          f"{ncap} capabilities + {next_} extension points → MAP.md; "
          f"ratchet: {stats['undocumented_modules']} undocumented modules, "
          f"{stats['undocumented_exports']} undocumented exports")


if __name__ == "__main__":
    main()
