// Deterministic ADR page generator for the Starlight docs site.
//
// Source of truth: docs/decisions/README.md (validated file-by-file by
// scripts/adr-index-check — every NNNN-*.md is indexed exactly once with a
// status matching its own `## Status` section) plus the ADR records themselves.
//
// It produces two kinds of output under src/content/docs/adrs/:
//   • index.mdx           the ADR landing page — a real, linked table whose
//                         rows point at the INTERNAL /adrs/<slug>/ pages below
//                         (TRACKED in git; kept in sync, gated by --check).
//   • <slug>.md           one Starlight page per ADR, transcribed faithfully
//                         from docs/decisions/<slug>.md (GITIGNORED — generated
//                         on every dev/build/check, never committed).
//
// Wired into the npm lifecycle (predev/prebuild/precheck), so `pnpm dev`,
// `pnpm build`, and `pnpm check` expose docs/decisions automatically — there is
// no manual `./dev adr-website` prerequisite. `./dev adr-website` delegates here
// so there is a single generator; its --check contract matches this lifecycle.
//
// Zero dependencies (Node stdlib only): the website build stays self-sufficient
// with just node/pnpm, and a clean `pnpm install --frozen-lockfile && pnpm
// build` regenerates everything.
//
// Modes:
//   node scripts/generate-adrs.mjs             (re)generate index + detail pages
//   node scripts/generate-adrs.mjs --check     fail (exit 1) if index.mdx drifted
//   node scripts/generate-adrs.mjs --self-test unit fixtures (doctor/CI)

import { readFileSync, writeFileSync, readdirSync, mkdirSync, unlinkSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..', '..');
const INDEX = join(REPO_ROOT, 'docs', 'decisions', 'README.md');
const DECISIONS = join(REPO_ROOT, 'docs', 'decisions');
const ADRS_DIR = join(REPO_ROOT, 'website', 'src', 'content', 'docs', 'adrs');
const INDEX_PAGE = join(ADRS_DIR, 'index.mdx');

// Detail pages link back into the site; the landing intro and any ADR link that
// escapes docs/decisions/ resolves to the canonical source tree on GitHub.
const GITHUB_BLOB = 'https://github.com/neohaskell/NeoHaskell/blob/main';
const README_URL = `${GITHUB_BLOB}/docs/decisions/README.md`;

// Same row shape scripts/adr-index-check validates:
//   | [0069](0069-security-reviews-are-local.md) | Title … | Accepted |
const ROW_RE = /^\|\s*\[(\d{4})\]\(([^)]+)\)\s*\|\s*(.+?)\s*\|\s*([^|]+?)\s*\|\s*$/;

const GENERATED_NOTICE =
  '{/* GENERATED by website/scripts/generate-adrs.mjs from docs/decisions/README.md — do not edit by hand.\n' +
  '    Regenerate: ./dev adr-website (or it runs automatically on pnpm predev/prebuild/precheck)\n' +
  '    Verify (CI): ./dev adr-website --check */}';

// ── pure helpers (unit-tested in --self-test) ──────────────────────────────

/** Rows of the ADR index table: [{num, file, slug, title, status}]. */
export function parseIndex(text) {
  const entries = [];
  for (const line of text.split('\n')) {
    const m = ROW_RE.exec(line);
    if (!m) continue; // header / separator / prose
    const [, num, file, title, status] = m;
    entries.push({ num, file: file.trim(), slug: file.trim().replace(/\.md$/, ''), title: title.trim(), status: status.trim() });
  }
  return entries;
}

/** Quote a string as a YAML double-quoted scalar (titles carry ':' and '`'). */
export function yamlQuote(s) {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

/** Normalize a path written relative to docs/decisions/ (resolves ./ and ../). */
export function resolveDocsPath(rel) {
  const stack = [];
  for (const part of `docs/decisions/${rel}`.split('/')) {
    if (part === '' || part === '.') continue;
    if (part === '..') stack.pop();
    else stack.push(part);
  }
  return stack.join('/');
}

/** Rewrite the links in an ADR body so they work on the website.
 *   NNNN-slug.md[#a]  → /adrs/NNNN-slug/[#a]   (internal ADR page)
 *   README.md[#a]     → /adrs/[#a]             (this landing page)
 *   other X.md[#a]    → GitHub source blob     (files not on the site)
 * Code fences are left untouched so example snippets are preserved verbatim. */
export function rewriteLinks(body) {
  const out = [];
  let inFence = false;
  for (const line of body.split('\n')) {
    if (/^\s*(```|~~~)/.test(line)) { inFence = !inFence; out.push(line); continue; }
    if (inFence) { out.push(line); continue; }
    let l = line;
    // README (index) links first — before the generic .md catch-all.
    l = l.replace(/\]\((?:\.\/)?README\.md(#[^)]*)?\)/g, (_m, anchor) => `](/adrs/${anchor || ''})`);
    // ADR-to-ADR links → internal detail route.
    l = l.replace(/\]\((?:\.\/)?(\d{4}-[A-Za-z0-9-]+)\.md(#[^)]*)?\)/g,
      (_m, slug, anchor) => `](/adrs/${slug}/${anchor || ''})`);
    // Any remaining relative *.md link points outside the site → GitHub source.
    l = l.replace(/\]\((?!https?:|\/|#|mailto:)([^)\s]+?\.md)(#[^)]*)?\)/g,
      (_m, rel, anchor) => `](${GITHUB_BLOB}/${resolveDocsPath(rel)}${anchor || ''})`);
    out.push(l);
  }
  return out.join('\n');
}

/** Split an ADR into its title (first H1) and the remaining body. */
export function extractTitle(raw, fallback) {
  const lines = raw.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const m = /^#\s+(.+?)\s*$/.exec(lines[i]); // H1 only ('## …' is a section)
    if (m) return { title: m[1], body: [...lines.slice(0, i), ...lines.slice(i + 1)].join('\n') };
  }
  return { title: fallback, body: raw };
}

/** A faithful Starlight page for one ADR: frontmatter + transcribed body. */
export function renderDetail(entry, raw) {
  const { title, body } = extractTitle(raw, entry.title);
  const transcribed = rewriteLinks(body).replace(/^\n+/, '').replace(/\s+$/, '');
  return `---\ntitle: ${yamlQuote(title)}\n---\n\n${transcribed}\n`;
}

/** The tracked ADR landing page — internal links, deterministic ordering. */
export function renderIndex(entries) {
  const rows = entries.map((e) => `| [${e.num}](/adrs/${e.slug}/) | ${e.title} | ${e.status} |`);
  return [
    '---',
    'title: Architecture Decision Records',
    'description: The architectural decisions behind NeoHaskell, with links to each record.',
    '---',
    '',
    'Architecture Decision Records (ADRs) capture the significant architectural decisions made while building NeoHaskell. Each record documents the **context** (why the decision was needed), the **decision** (what was chosen and why), and the **consequences** (what follows from it).',
    '',
    `ADRs are immutable: when a decision is reversed, a new ADR is written that references the original. Each record below is published as its own page, transcribed from the [decisions log](${README_URL}) in the repository — the records themselves are maintained in English.`,
    '',
    GENERATED_NOTICE,
    '',
    '| ADR | Title | Status |',
    '| --- | ----- | ------ |',
    ...rows,
    '',
  ].join('\n');
}

// ── filesystem actions ─────────────────────────────────────────────────────

function readEntries() {
  return parseIndex(readFileSync(INDEX, 'utf8'));
}

function writeDetails(entries) {
  mkdirSync(ADRS_DIR, { recursive: true });
  const wanted = new Set();
  for (const e of entries) {
    wanted.add(e.slug);
    const raw = readFileSync(join(DECISIONS, e.file), 'utf8');
    writeFileSync(join(ADRS_DIR, `${e.slug}.md`), renderDetail(e, raw), 'utf8');
  }
  return pruneStale(wanted);
}

/** Remove generated detail pages (only *.md; never the tracked index.mdx) that
 *  no longer correspond to an ADR, so the output is deterministic. */
function pruneStale(wantedSlugs) {
  const removed = [];
  if (!existsSync(ADRS_DIR)) return removed;
  for (const f of readdirSync(ADRS_DIR)) {
    if (!f.endsWith('.md')) continue; // index.mdx and anything non-.md is safe
    if (!wantedSlugs.has(f.slice(0, -3))) { unlinkSync(join(ADRS_DIR, f)); removed.push(f); }
  }
  return removed.sort();
}

function cmdWrite() {
  const entries = readEntries();
  mkdirSync(ADRS_DIR, { recursive: true });
  writeFileSync(INDEX_PAGE, renderIndex(entries), 'utf8');
  const removed = writeDetails(entries);
  const extra = removed.length ? `, pruned ${removed.length} stale` : '';
  console.log(`adr-website: wrote index.mdx + ${entries.length} ADR pages${extra}`);
  return 0;
}

function cmdCheck() {
  const entries = readEntries();
  // Regenerate the (gitignored) detail pages so --check also proves every ADR
  // still transcribes without error; then gate the one TRACKED file for drift.
  writeDetails(entries);
  const want = renderIndex(entries);
  if (!existsSync(INDEX_PAGE)) {
    console.error(`adr-website: FAIL — ${rel(INDEX_PAGE)} is missing; run ./dev adr-website`);
    return 1;
  }
  if (readFileSync(INDEX_PAGE, 'utf8') !== want) {
    console.error(`adr-website: FAIL — ${rel(INDEX_PAGE)} is out of sync with docs/decisions/README.md`);
    console.error('  regenerate with: ./dev adr-website');
    return 1;
  }
  console.log(`adr-website: OK — ADR landing page in sync (${entries.length} ADRs), detail pages regenerated`);
  return 0;
}

function rel(p) {
  return p.startsWith(REPO_ROOT) ? p.slice(REPO_ROOT.length + 1) : p;
}

// ── self-test (fixtures; no writes to the real tree) ───────────────────────

function selfTest() {
  let ok = true;
  const check = (name, cond) => { console.log(`  ${cond ? 'ok  ' : 'FAIL'} ${name}`); ok = ok && cond; };

  const sample =
    '# Architecture Decision Records (ADRs)\n\n' +
    '| ADR | Title | Status |\n' +
    '| --- | ----- | ------ |\n' +
    '| [0001](0001-initial-architecture-baseline.md) | Initial Baseline | Accepted |\n' +
    '| [0055](0055-declarative-integrations-with-fakes.md) | Declarative Integrations | Proposed |\n\n' +
    '## Creating New ADRs\n';
  const entries = parseIndex(sample);
  check('parses exactly the two data rows (header/separator skipped)', entries.length === 2);
  check('captures number/file/slug/title/status',
    entries[0].num === '0001' && entries[0].slug === '0001-initial-architecture-baseline' &&
    entries[0].title === 'Initial Baseline' && entries[0].status === 'Accepted');
  check('preserves Proposed status', entries[1].status === 'Proposed');

  const idx = renderIndex(entries);
  check('index rows link INTERNALLY to /adrs/<slug>/', idx.includes('| [0001](/adrs/0001-initial-architecture-baseline/) |'));
  check('index carries no GitHub blob link in its rows', !/\]\(https:\/\/github\.com[^)]*\)\s*\|/.test(idx));
  check('index carries the generated banner', idx.includes('GENERATED by website/scripts/generate-adrs.mjs'));
  check('index has valid frontmatter', idx.startsWith('---\ntitle: Architecture Decision Records'));
  check('index render is deterministic', renderIndex(entries) === idx);

  const t = extractTitle('# ADR-0069: Local, never pushed\n\n## Status\n\nAccepted\n', 'fallback');
  check('extractTitle takes the first H1', t.title === 'ADR-0069: Local, never pushed');
  check('extractTitle keeps ## sections in the body', t.body.includes('## Status') && !t.body.includes('# ADR-0069'));

  const rw = rewriteLinks('See [x](0067-contract-delta-spec-gate.md) and [y](0067-contract-delta-spec-gate.md#status) and [i](README.md) and [p](../plans/foo.md).');
  check('rewrites ADR link to internal route', rw.includes('](/adrs/0067-contract-delta-spec-gate/)'));
  check('rewrites ADR link + anchor', rw.includes('](/adrs/0067-contract-delta-spec-gate/#status)'));
  check('rewrites README link to /adrs/', rw.includes('](/adrs/)'));
  check('rewrites off-site .md link to GitHub source', rw.includes(`](${GITHUB_BLOB}/docs/plans/foo.md)`));

  const fenced = rewriteLinks('```\n[keep](0001-x.md)\n```\n[go](0001-real-slug.md)');
  check('leaves links inside code fences untouched', fenced.includes('[keep](0001-x.md)'));
  check('still rewrites links outside fences', fenced.includes('](/adrs/0001-real-slug/)'));

  const detail = renderDetail({ slug: '0069-x', title: 'fallback' }, '# ADR-0069: Title: with colon\n\nBody [ref](0001-a.md).\n');
  check('detail frontmatter quotes a title containing a colon', detail.includes('title: "ADR-0069: Title: with colon"'));
  check('detail strips the source H1', !detail.includes('# ADR-0069: Title: with colon\n'));
  check('detail rewrites body links', detail.includes('](/adrs/0001-a/)'));

  check('yamlQuote escapes embedded quotes', yamlQuote('a "b" c') === '"a \\"b\\" c"');
  check('resolveDocsPath normalizes ../', resolveDocsPath('../plans/x.md') === 'docs/plans/x.md');

  console.log('adr-website: self-test', ok ? 'OK' : 'FAILED');
  return ok ? 0 : 1;
}

// ── entry point ─────────────────────────────────────────────────────────────

function main(argv) {
  const mode = argv[0];
  if (mode === '--self-test') return selfTest();
  if (mode === '--check') return cmdCheck();
  if (!mode) return cmdWrite();
  console.error(`usage: generate-adrs.mjs [--check|--self-test]  (got ${JSON.stringify(argv)})`);
  return 2;
}

process.exit(main(process.argv.slice(2)));
