#!/bin/bash

cabal install doctest --overwrite-policy=always && cabal build all && cabal repl --build-depends=QuickCheck --build-depends=template-haskell --with-ghc=doctest --repl-options='-w -Wdefault'