{ pkgs }:
{ neoConfig, modules, neoHaskellSource ? null }:
let
  inherit (neoConfig) name version description license author dependencies;
  common = import ../common.nix { inherit pkgs; };

  execName = pkgs.lib.toLower (builtins.replaceStrings [ " " ] [ "-" ] name);

  makeDep = dep: version:
    if pkgs.lib.hasPrefix "^" version then
      "${dep} ^>= ${pkgs.lib.removePrefix "^" version}"
    else
      "${dep} == ${version}";

  deps = pkgs.lib.concatStringsSep ", "
    ((pkgs.lib.mapAttrsToList makeDep dependencies) ++ [ "nhcore" ]);

  moduleList = pkgs.lib.concatStringsSep ", " modules;

  # Format GHC options for cabal file
  ghcOptionsStr =
    pkgs.lib.concatStringsSep "\n                    " common.ghcOptions;
  extensionsStr =
    pkgs.lib.concatStringsSep "\n      " common.languageExtensions;


in ''
  cabal-version:      3.4
  -- THIS CABAL FILE IS AUTOGENERATED BY `neo`, THE NEOHASKELL CLI TOOL.
  -- YOU SHOULD NOT MODIFY IT, AS IT WILL BE REGENERATED NEXT TIME `neo` RUNS.
  --
  -- IF YOU HAVE A SPECIFIC NEED TO MODIFY THIS
  -- FILE, PLEASE STATE SO EITHER IN A GITHUB
  -- ISSUE: https://github.com/NeoHaskell/NeoHaskell/issues
  -- OR IN THE NEOHASKELL DISCORD SERVER.
  -- YOU CAN JOIN IT THROUGH THE LINK IN
  -- https://neohaskell.org
  name:               ${name}
  version:            ${version}
  synopsis:           ${description}
  license:            ${license}
  author:             ${author}

  common common_cfg
      ghc-options:    ${ghcOptionsStr}
      default-language: GHC2021
      default-extensions:
        ${extensionsStr}

      build-depends:
        ${deps}

  library
      import:           common_cfg
      exposed-modules:
        ${moduleList}
      hs-source-dirs:   src

  executable ${execName}
      import:           common_cfg
      main-is:          Main.hs
      build-depends:
          ${name}
      hs-source-dirs:   app
''
