{ pkgs }:
{ neoHaskellCommit ? null }:

let
  sourceRepoPackage = if neoHaskellCommit != null then ''
source-repository-package
    type: git
    location: https://github.com/NeoHaskell/NeoHaskell
    tag: ${neoHaskellCommit}
    subdir: core
    --sha256: 0000000000000000000000000000000000000000000000000000

'' else "";

in ''
-- THIS CABAL.PROJECT FILE IS AUTOGENERATED BY `neo`, THE NEOHASKELL CLI TOOL.
-- YOU SHOULD NOT MODIFY IT, AS IT WILL BE REGENERATED NEXT TIME `neo` RUNS.

${sourceRepoPackage}packages: .
''