name: "Populate Cachix"

on:
  push:
    branches:
      - main
    paths:
      - "core/**"
      - "testbed/**"
      - "integrations/**"
      - "nix/**"
      - ".github/workflows/**"

jobs:
  cachix-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3.17.1
        with:
          extra-conf: |
            accept-flake-config = true
            extra-substituters = https://cache.iog.io https://neohaskell.cachix.org
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= neohaskell.cachix.org-1:mo2cLaGbwqbrxs9xhqKK8jeNsn3osi7t6XoAmxSZssc=
      - uses: cachix/cachix-action@v17
        with:
          name: neohaskell
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build to populate cache
        run: nix develop --command cabal build all --disable-documentation
